version: '3'
services:
  php-nginx:
    image: webdevops/php-nginx
    ports:
      - "8081:80"
    volumes : 
      - ./app:/app
    links : 
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes : 
     - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  #html2pdf:
    #image: protodype/html2pdf
    #ports:
     # - "8082:80"
